name: scrap-bcsd-update-output

on:
  schedule:
    - cron: "30 23 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8" # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: install Playwright
        run: |
          playwright install

      - name: execute py script # run sj-gobierno.py to get the latest data
        run: python bcsd_covidtrack.py

      - name: commit files
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Scraped by Github actions on ${{ steps.date.outputs.date }}"
          git push
